# Generated by Django 3.2.9 on 2021-11-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passworld',
            new_name='Cadastro',
        ),
    ]
