# Generated by Django 3.2.9 on 2021-11-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_passworld_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
