# Generated by Django 3.2.9 on 2021-11-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_cadastro_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='confirm_passworld',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='passworld',
            new_name='password',
        ),
    ]
